### ISSUE TITLE
[BUG] Build error with Python 3.13: ‘_Py_SetProgramFullPath’ was not declared in this scope

### ISSUE THREAD

**Issue by pulver** [DataDog/datadog-agent#34076]
When building with Python 3.13 running `invoke agent.build` results in a compiler error:
```
...
[ 29%] Building CXX object three/CMakeFiles/datadog-agent-three.dir/three.cpp.o
...
datadog-agent/rtloader/three/three.cpp:88:5: error: ‘_Py_SetProgramFullPath’ was not declared in this scope; did you mean ‘Py_GetProgramFullPath’?
   88 |     _Py_SetProgramFullPath(_pythonExe);
      |     ^~~~~~~~~~~~~~~~~~~~~~
      |     Py_GetProgramFullPath
```

**Agent Environment**

OS: Arch linux (2024-02-16)

Will submit a PR shortly.

**Comment by sgnn7** [comment]
Hi @pulver / @mattpulver ,
We are aware of this upcoming issue. As [mentioned](https://github.com/DataDog/datadog-agent/pull/34077#discussion_r1959905450) by @vickenty in the PR itself, limiting this API call to only supported Python versions without per-platform filtering will just obscure the fact that Python v3.13+ builds will not be able to fully support `multiprocessing` on Windows (used in some integrations OOTB). This is why the optimal fix needs to involve a bit more work to [enable PyConfig initialization](https://github.com/DataDog/datadog-agent/blob/main/rtloader/three/three.cpp#L83-L87). We can leave this ticket open but the related opened PR as-is will not likely be integrated into the codebase.

**Comment by thotypous** [comment]
This is now blocking datadog-agent from being built on Nix as well: https://hydra.nixos.org/build/300316089/nixlog/2

**Comment by sgnn7** [comment]
Hi everyone,
This specific error should have already been fixed with https://github.com/DataDog/datadog-agent/pull/35796 back in April and is available in `7.67.x`+ branches as well as `main`. We did not yet work on upgrading to Python 3.13 internally but I believe that this was the critical blocker.

I'll close the issue since the problem should be fixed but feel free to reopen if needed.
