### PR TITLE
[dsd] resolve container id for origin detection

### PR DESCRIPTION
**Pull request by xvello**
### What does this PR do?

- temporarily copy [process-agent's cgroup.go](https://github.com/DataDog/datadog-process-agent/blob/e44b0de7b9eb7f05c96a2dbf91e763e931bf6174/util/docker/cgroup.go), source will be merged there when stable
- update uds_linux.go, introduced by #463
- create origin_detection_test.go integration test
- improve UDS & UDP test coverage

### Current limitations

- PID -> container resolution is a quick `proc` file parsing away, so we do it synchronously and cache it for 5 minutes in gocache. As detecting processes ending would be costly, we can't invalidate the cache selectively. Best alternative would be to expire entries `x` seconds after the last access (last packet sent from that process), but gocache does not implement that out of the box.
- Although we resolve the container id as soon as possible, there's a possible race condition if the process exits just after submitting the metric. That means submitting with ephemeral processes like `netcat` is not viable.

### Additional Notes

gitlab runner can't run this test, launch by running:

`go test ./test/integration/dogstatsd/origin_detection_test.go` on a docker host

### CODE REVIEW

**Review by masci — APPROVED** [review]
🍰
