### PR TITLE
[SVLS 4506] serverless sidecar rebasemain3

### PR DESCRIPTION
**Pull request by jcstorms1**
### What does this PR do?
Modifies serverless-init to run as an independent sidecar rather than a process that wraps an application. Previously serverless-init was used only as a wrapper for an application. This allows us to reuse serverless-init in a wide range of use cases across cloud providers.

### Motivation
Google Cloud Run and Azure App Services have both introduced the ability to run sidecars in their platform. This will allow customers to receive traces, metrics and logs, when previously only one or two of these was acheivable.

### Describe how to test/QA your changes
Unit and integration testing.
Self-monitoring applications.

### CODE REVIEW

**Review by GustavoCaso — CHANGES_REQUESTED** [review]
Hey @jcstorms1 👋 

Wondering of you could provide a it more information on these changes. We are currently working from the Agent Shared Components to reduce the binary size of the serverless agent. Your changes seems to be adding a few packages that were not used before in the serverless agent. Could you provide more information why we need those packages?

Also, I noticed you deleted the `telemetry_noop*.go` files and build tags for `serverless` . On a previous PR we removed prometheus from the serverless binary https://github.com/DataDog/datadog-agent/pull/24854. Could you give some context on why you removed those files?

**Comment by GustavoCaso** [comment]
@alexgallotta Thank you so much for the details answer. I have some follow up questions:

> The serverless sidecar needs to read logs form a file. It was not using the fx framework before, so adding it and the required audiscovery module using the current components and framework, a bunch of dependencies were added such as:
  autodiscovery
  tagger module
  "workdloadmeta"
  default configs

That is quite unfortunate for the work that we have been task with, which includes removing the tagger and workloadmeta component from the serverless binary.

https://github.com/DataDog/datadog-agent/pull/24922
https://datadoghq.atlassian.net/browse/ASCII-1456

Also, the autodiscovery component is massive, which might bring to much overhead to the serverless binary. Why do we need it? maybe we can find some other way to get it working without this components? (tagger, workloadmetad, autodicovery)

> The serverless sidecar needs to read logs form a file.

Could you elaborate more on it? Can it just simply read the log file without using the whole `pkg/logs` package? 


> I tried to remove some serverless tags since they made handling the code harder, and there is a mix of flags and build tags used in different ways to build the agent. I am not sure if this is causing issue or increasing the agent side, I hoped a test or review would catch any issue.

For that particular case those tags was ensuring that the telemetry component would not bring the prometheus dependencies in the serverless binary.

File: comp/logs/agent/agentimpl/serverless.go [hunk 1]
```diff
@@ -7,6 +7,7 @@ package agentimpl
 
 import (
 	"context"
+	flareController "github.com/DataDog/datadog-agent/comp/logs/agent/flare"
```
Comment (GustavoCaso) [inline comp/logs/agent/agentimpl/serverless.go:10]: Do we have flares within the serverless context?

File: cmd/serverless-init/main.go [hunk 2]
```diff
@@ -8,108 +8,122 @@
 package main
 
 import (
+	"context"
+	serverlessInitLog "github.com/DataDog/datadog-agent/cmd/serverless-init/log"
+	"github.com/DataDog/datadog-agent/cmd/serverless-init/mode"
+	"github.com/DataDog/datadog-agent/comp/core"
+	"github.com/DataDog/datadog-agent/comp/core/autodiscovery"
+	"github.com/DataDog/datadog-agent/comp/core/autodiscovery/autodiscoveryimpl"
```
Comment (GustavoCaso) [inline cmd/serverless-init/main.go:16]: Do we need this component in the serverless binary?

File: cmd/serverless-init/main.go [hunk 3]
```diff
@@ -8,108 +8,122 @@
...
+	coreconfig "github.com/DataDog/datadog-agent/comp/core/config"
+	healthprobeDef "github.com/DataDog/datadog-agent/comp/core/healthprobe/def"
+	healthprobeFx "github.com/DataDog/datadog-agent/comp/core/healthprobe/fx"
+	"github.com/DataDog/datadog-agent/comp/core/log/logimpl"
+	"github.com/DataDog/datadog-agent/comp/core/secrets"
+	"github.com/DataDog/datadog-agent/comp/core/tagger"
+	"github.com/DataDog/datadog-agent/comp/core/tagger/taggerimpl"
+	"github.com/DataDog/datadog-agent/comp/core/workloadmeta"
```
Comment (GustavoCaso) [inline cmd/serverless-init/main.go:24]: Do we need this component in the serverless binary?

File: comp/logs/agent/agentimpl/serverless.go (hunk 1 above)
Comment (alexgallotta) [reply comp/logs/agent/agentimpl/serverless.go:10]: I had to add it otherwise a null crash would happen here
https://github.com/DataDog/datadog-agent/commit/3af304da7c2cd4dd9de77ae59d5f8c8d9a29cee0

File: cmd/serverless-init/main.go (hunk 2 above)
Comment (alexgallotta) [reply cmd/serverless-init/main.go:16]: replying in the thread above for autodiscovery+workloadmeta

File: cmd/serverless-init/main.go (hunk 3 above)
Comment (alexgallotta) [reply cmd/serverless-init/main.go:24]: replying in the thread above for autodiscovery+workloadmeta

File: comp/logs/agent/agentimpl/agent_serverless_init.go [hunk 4]
```diff
@@ -16,22 +16,28 @@ import (
...
+	"github.com/DataDog/datadog-agent/pkg/logs/launchers/container"
+	filelauncher "github.com/DataDog/datadog-agent/pkg/logs/launchers/file"
+	"github.com/DataDog/datadog-agent/pkg/logs/launchers/journald"
+	"github.com/DataDog/datadog-agent/pkg/logs/launchers/listener"
+	"github.com/DataDog/datadog-agent/pkg/logs/launchers/windowsevent"
 	"github.com/DataDog/datadog-agent/pkg/logs/pipeline"
 	"github.com/DataDog/datadog-agent/pkg/logs/schedulers"
 	"github.com/DataDog/datadog-agent/pkg/status/health"
 	"github.com/DataDog/datadog-agent/pkg/util/optional"
+	"time"
```
[the remark this answers is not in the document]
Comment (alexgallotta) [reply comp/logs/agent/agentimpl/agent_serverless_init.go:28]: I will try to do it manually.
Should it be enforced by an automated test?

File: pkg/logs/launchers/file/launcher.go [hunk 5]
```diff
@@ -195,7 +195,6 @@ func (s *Launcher) scan() {
 
 		filesTailed[scanKey] = true
 	}
-
```
[the remark this answers is not in the document]
Comment (alexgallotta) [reply pkg/logs/launchers/file/launcher.go]: done!

File: pkg/logs/schedulers/ad/scheduler.go [hunk 6]
```diff
@@ -80,7 +81,7 @@ func (s *Scheduler) Schedule(configs []integration.Config) {
 				s.mgr.AddSource(source)
 			}
 		default:
-			// invalid integration config
+			log.Debugf("Invalid integration config: %s, ignoring it", s.configName(config))
```
[the remark this answers is not in the document]
Comment (alexgallotta) [reply pkg/logs/schedulers/ad/scheduler.go:84]: I tried to stick with the format of another log above
https://github.com/DataDog/datadog-agent/blob/main/pkg/logs/schedulers/ad/scheduler.go#L73

That case seems to be only when this is false
https://github.com/DataDog/datadog-agent/blob/main/pkg/logs/schedulers/ad/scheduler.go#L127

I am not sure what this means
```
// newSources returns true if the config can be mapped to sources.
func (s *Scheduler) newSources(config integration.Config) bool {
return config.Provider != ""
```
a non null string in provider means it can be mapped to source? But source are not mandatory I think, or appear to be arbitrary. I didn't dig into that

File: comp/logs/agent/agentimpl/agent_serverless_init.go [hunk 7]
```diff
@@ -47,6 +53,16 @@ func (a *logAgent) SetupPipeline(
 	// setup the sole launcher for this agent
```
[the remark this answers is not in the document]
Comment (alexgallotta) [reply comp/logs/agent/agentimpl/agent_serverless_init.go:53]: Right, deleting it!

File: comp/logs/agent/agentimpl/agent_serverless_init.go [hunk 8]
```diff
@@ -47,6 +53,16 @@ func (a *logAgent) SetupPipeline(
...
+	lnchrs.AddLauncher(filelauncher.NewLauncher(
+		a.config.GetInt("logs_config.open_files_limit"),
+		filelauncher.DefaultSleepDuration,
+		a.config.GetBool("logs_config.validate_pod_container_id"),
+		time.Duration(a.config.GetFloat64("logs_config.file_scan_period")*float64(time.Second)),
+		a.config.GetString("logs_config.file_wildcard_selection_mode"), a.flarecontroller))
+	lnchrs.AddLauncher(listener.NewLauncher(a.config.GetInt("logs_config.frame_size")))
+	lnchrs.AddLauncher(journald.NewLauncher(a.flarecontroller))
+	lnchrs.AddLauncher(windowsevent.NewLauncher())
+	lnchrs.AddLauncher(container.NewLauncher(a.sources, wmeta))
```
[the remark this answers is not in the document]
Comment (alexgallotta) [reply comp/logs/agent/agentimpl/agent_serverless_init.go:65]: From the naming, that seems overkill for serverless.
I tried to remove them line by line but they were causing errors somewhere

File: comp/logs/agent/agentimpl/agent_serverless_init.go [hunk 9]
```diff
@@ -47,6 +53,16 @@ func (a *logAgent) SetupPipeline(
 	// setup the sole launcher for this agent
 	lnchrs := launchers.NewLaunchers(a.sources, pipelineProvider, a.auditor, a.tracker)
 	lnchrs.AddLauncher(channel.NewLauncher())
+	lnchrs.AddLauncher(filelauncher.NewLauncher(
```
[the remark this answers is not in the document]
Comment (alexgallotta) [reply comp/logs/agent/agentimpl/agent_serverless_init.go:56]: I didn't see any errors due to that. Is it an event which would happen in some specific condition or it should be happening continuously?

**Comment by alexgallotta** [comment]
> @alexgallotta Thank you so much for the details answer. I have some follow up questions:
> 
> > The serverless sidecar needs to read logs form a file. It was not using the fx framework before, so adding it and the required audiscovery module using the current components and framework, a bunch of dependencies were added such as:
> > autodiscovery
> > tagger module
> > "workdloadmeta"
> > default configs
> 
> That is quite unfortunate for the work that we have been task with, which includes removing the tagger and workloadmeta component from the serverless binary.
> 
> #24922 https://datadoghq.atlassian.net/browse/ASCII-1456
> 
> Also, the autodiscovery component is massive, which might bring to much overhead to the serverless binary. Why do we need it? maybe we can find some other way to get it working without this components? (tagger, workloadmetad, autodicovery)
> 
> > The serverless sidecar needs to read logs form a file.
> 
> Could you elaborate more on it? Can it just simply read the log file without using the whole `pkg/logs` package?
> 
> > I tried to remove some serverless tags since they made handling the code harder, and there is a mix of flags and build tags used in different ways to build the agent. I am not sure if this is causing issue or increasing the agent side, I hoped a test or review would catch any issue.
> 
> For that particular case those tags was ensuring that the telemetry component would not bring the prometheus dependencies in the serverless binary.

about autodiscovery, I would be more than happy to remove as much dependencies as possible, but this is the pattern we are using:
- users define a path with regexp that can select one or multiple files
- the agent will check if files matching the regexp exist and tail them to send logs

I assumed this is what autodiscovery itself does, or it's a strict dependency of it

For the prometheus dependencies, I'm ok to re add the tags. I am not sure if the impact is that big though, since the size seem to be the same

File: comp/logs/agent/agentimpl/agent_serverless_init.go (hunk 8 above)
[the remark this answers is not in the document]
Comment (alexgallotta) [reply comp/logs/agent/agentimpl/agent_serverless_init.go:65]: It sounds like a good solution. I tried to build now but the build fails because of some bad merge or conflict
```
../../comp/core/telemetry/telemetryimpl/telemetry.go:66:9: cannot use &telemetryImpl{…} (value of type *telemetryImpl) as telemetry.Component value in return statement: *telemetryImpl does not implement telemetry.Component (wrong type for method Meter)
                have Meter(string, ...telemetry.MeterOption) "go.opentelemetry.io/otel/metric".Meter
                want Meter(string, ...telemetry.MeterOption) telemetry.Meter
../../comp/core/telemetry/telemetryimpl/telemetry.go:103:37: cannot use opts (variable of type []telemetry.MeterOption) as []"go.opentelemetry.io/otel/metric".MeterOption value in argument to t.meterProvider.Meter
../../comp/core/telemetry/telemetryimpl/telemetry.go:252:10: cannot use t.defaultRegistry.Gather() (value of type []*io_prometheus_client.MetricFamily) as []*telemetry.MetricFamily value in return statement
../../comp/core/telemetry/telemetryimpl/telemetry.go:258:9: cannot use registry.Gather() (value of type []*io_prometheus_client.MetricFamily) as []*telemetry.MetricFamily value in return statement
```
I will sync up with @jcstorms1 and decide on next steps, likely rebase everything, fix compilation and try to remove those launchers

**Review by zhuminyi — APPROVED** [review]
LGTM

File: cmd/serverless-init/main.go [hunk 10]
```diff
@@ -8,108 +8,126 @@
...
+		os.Exit(-1)
 	}
 }
 
-func run(cliParams *cliParams) {
-	cloudService, logConfig, traceAgent, metricAgent, logsAgent := setup()
-	initcontainer.Run(cloudService, logConfig, metricAgent, traceAgent, logsAgent, cliParams.args)
-}
+// removing these unused dependencies will cause silent crash due to fx framework
+func run(_ secrets.Component, _ autodiscovery.Component, _ healthprobeDef.Component) {
```
Comment (GustavoCaso) [inline cmd/serverless-init/main.go:90]: We could provide the config component to the run function and later to the setup function, and do not relay on confog.Datadog(), but the actual config component.

File: cmd/serverless-init/main.go [hunk 11]
```diff
@@ -8,108 +8,126 @@
...
+	agentLogConfig := serverlessInitLog.CreateConfig(origin)
 
 	// The datadog-agent requires Load to be called or it could
 	// panic down the line.
-	_, err := config.LoadWithoutSecret()
+	_, err := pkgconfig.LoadWithoutSecret()
 	if err != nil {
-		logger.Debugf("Error loading config: %v\n", err)
+		log.Debugf("Error loading config: %v\n", err)
 	}
```
Comment (GustavoCaso) [inline cmd/serverless-init/main.go:129]: Since you are using Fx to load certain components and one of them being the config component, I believe you have access to the config object through the config component, so we could remove this line and use the config component down the stack. 

This probably requires a bit of refactoring in the different elements of the serverless init, which would require passing the config component to the different functions. Such as `setupTraceAgent`, `setupMetricAgent ` and any other function that uses the config.

Let me know if it clear and if not I'm more than happy to pair to on it.

File: cmd/serverless-init/main.go [hunk 12]
```diff
@@ -8,108 +8,126 @@
...
+	metric.AddShutdownMetric(cloudService.GetPrefix(), metricAgent.GetExtraTags(), time.Now(), metricAgent.Demux)
+	lastFlush(logConfig.FlushTimeout, metricAgent, traceAgent, logsAgent)
+}
 
+func setup(mode.Conf) (cloudservice.CloudService, *serverlessInitLog.Config, *trace.ServerlessTraceAgent, *metrics.ServerlessMetricAgent, logsAgent.ServerlessLogsAgent) {
 	tracelog.SetLogger(corelogger{})
 
 	// load proxy settings
-	config.LoadProxyFromEnv(config.Datadog())
+	pkgconfig.LoadProxyFromEnv(pkgconfig.Datadog())
```
Comment (GustavoCaso) [inline cmd/serverless-init/main.go:103]: Do we need to proxy settings in the serverless context?

File: cmd/serverless-init/main.go [hunk 13]
```diff
@@ -8,108 +8,126 @@
...
+		}),
+		taggerimpl.Module(),
+		healthprobeFx.Module(),
+		fx.Supply(workloadmeta.NewParams()),
+		fx.Supply(tagger.NewTaggerParams()),
+		fx.Supply(core.BundleParams{
+			ConfigParams: coreconfig.NewParams("", coreconfig.WithConfigMissingOK(true)),
+			SecretParams: secrets.NewEnabledParams(),
+			LogParams:    logimpl.ForOneShot(modeConf.LoggerName, "off", true)}),
+		core.Bundle(),
```
Comment (GustavoCaso) [inline cmd/serverless-init/main.go:80]: The core bundle is overkill for the serverless binary. 

It brings useful components and at the same time a few other components that do not make sense in the serverless environment, such as the telemetry component, the system probe config component. 

I think for this case rather than using the bundle, we should include manually the component that we need in the serverless init context. Secrets, Logs, and Config 


```go
fx.Supply(coreconfig.NewParams("", coreconfig.WithConfigMissingOK(true))),
coreconfig.Module(),
fx.Supply(secrets.NewEnabledParams()),
secretsimpl.Module(),
fx.Supply(logimpl.ForOneShot(modeConf.LoggerName, "off", true)),
logimpl.Module(),
```

File: cmd/serverless-init/main.go [hunk 14]
```diff
@@ -8,108 +8,126 @@
...
 	"github.com/DataDog/datadog-agent/pkg/serverless/metrics"
 	"github.com/DataDog/datadog-agent/pkg/serverless/otlp"
 	"github.com/DataDog/datadog-agent/pkg/serverless/random"
-	"github.com/DataDog/datadog-agent/pkg/serverless/tags"
+	serverlessTag "github.com/DataDog/datadog-agent/pkg/serverless/tags"
 	"github.com/DataDog/datadog-agent/pkg/serverless/trace"
 	tracelog "github.com/DataDog/datadog-agent/pkg/trace/log"
 	"github.com/DataDog/datadog-agent/pkg/util/fxutil"
-	logger "github.com/DataDog/datadog-agent/pkg/util/log"
+	"github.com/DataDog/datadog-agent/pkg/util/log"
```
Comment (GustavoCaso) [inline cmd/serverless-init/main.go:50]: Since we are using the log component is better to not require the log package `"github.com/DataDog/datadog-agent/pkg/util/log"` and use the log component which is a wrapper around that `"github.com/DataDog/datadog-agent/pkg/util/log"` package. 

You can pass the log component to the functions and other packages from the run function

File: cmd/serverless-init/main.go (hunk 12 above)
Comment (alexgallotta) [reply cmd/serverless-init/main.go:104]: Not sure about that, it wasn't changed from before
https://github.com/DataDog/datadog-agent/blob/main/cmd/serverless-init/main.go#L88

Do you think it is a good idea to merge this PR and address the config refactoring in another?

**Review by GustavoCaso — APPROVED** [review]
Unblocking the PR, but there are a few things that would be good to validate and refactor in following PRs:
- Validate the need to call `pkgconfig.LoadProxyFromEnv(pkgconfig.Datadog())`. Do we run the serverless-init as a proxy, or using fips? If not we shuld probably remove that line
- Calling `_, err := pkgconfig.LoadWithoutSecret()` We are using the config component, I don't think we need to call this function as the configuration has been loaded via the config component 
- The `run` does not use any component. It would be good propagate the different components to the setup function to use them. For example the config component instead of using `pkgconfig.Datadog()`, and the logs component, that way we can avoid importing the `pkg/log` entirely 😄 
- Validate that we need all the components that we have declared: `autodiscoivery`, `workloadmeta`, `tagger`, and `healthprobe`

**Review by alexgallotta — APPROVED** [review]

**Review by knusbaum — APPROVED** [review]

**Review by gh123man — APPROVED** [review]
AML files LGTM. Discussed auditor concerns offline.

File: comp/logs/agent/agentimpl/agent_serverless_init.go (hunk 9 above)
[the remark this answers is not in the document]
Comment (alexgallotta) [reply comp/logs/agent/agentimpl/agent_serverless_init.go:53]: I see! Since we use it in lambda extension, I think the case of collecting the logs from where we left off is not an issue

[the remark this answers is not in the document]
Comment (jcstorms1) [reply comp/logs/agent/agentimpl/agent_serverless_init.go:53]: I will look into this next in a new PR. I believe this is only a concern for Azure App Service in certain situations.
