### ISSUE TITLE
[BUG] `pkg/util/log`: test-only helpers use a non-standard `//go:build test` tag instead of `_test.go` naming

### ISSUE THREAD

**Issue by darccio** [DataDog/datadog-agent#55023]
### Agent version

v0.82.0

### Summary

Several files in `pkg/util/log` (and its `slog`, `slog/formatters`, `slog/handlers`, and transitively `zap` subpackages) gate test-helper code behind a custom `//go:build test` constraint instead of using the standard Go convention of a `_test.go` filename suffix:

- `pkg/util/log/logger_test_utils.go`
- `pkg/util/log/log_test_init.go`
- `pkg/util/log/slog/logger_test_utils.go`
- `pkg/util/log/slog/formatters/template.go`
- `pkg/util/log/slog/handlers/test_utils.go`

These define symbols (`LoggerFromWriterWithMinLevelAndLvlFuncMsgFormat`, `LoggerFromWriterWithMinLevelAndLvlFuncCtxMsgFormat`, `Template`, `newMockInnerHandler`, etc.) that real `_test.go` files in the same packages reference unconditionally — including `log_test.go`, `log_bench_test.go`, `klog_redirect_test.go`, `wrapper_test.go`, `pkg/util/log/slog/formatters/template_test.go`, `pkg/util/log/slog/handlers/async_test.go`, and (transitively, via `slog.LoggerFromWriterWithMinLevelAndFormat`) `pkg/util/log/zap/zapcore_test.go`.

Inside this repo, the gap is invisible: `dda inv test` and this repo's own Bazel setup (`bazel/rules/go/dd_agent_go_test.bzl`'s `dd_agent_go_test` macro) both know to add `"test"` to the build tags for test targets — `UNIT_TEST_TAGS`/`BASE_TEST_TAGS` in `tasks/build_tags.bzl` include it — while production targets (`dd_agent_go_binary`, using `COMMON_TAGS`) deliberately don't. Because rules_go's `gotags` attribute is a per-target build configuration transition rather than a global flag, the *same* `go_library` (e.g. `pkg/util/log/BUILD.bazel`, which already lists these files as `go_library` srcs, not `go_test` srcs) compiles differently depending on whether it's pulled in by a test target or a production binary target. So within this repo's own tooling, everything works, and `log_test_init.go`'s `init()` never reaches a production binary.

That safety net only exists because of this repo's custom macros. It disappears the moment `pkg/util/log` is consumed the normal way: as a versioned Go module (`go get github.com/DataDog/datadog-agent/pkg/util/log`, currently tagged through `v0.82.1`) built with stock `go build`/`go test`/`go vet`/`golangci-lint`, or with a plain Gazelle setup that has no equivalent of `dd_agent_go_test`'s tag wiring. Such tooling has no way to know it needs `-tags test`, so:

1. **Its own tests on this package fail to compile** — `go vet`/`go test` on `pkg/util/log` (and `slog`, `slog/formatters`, `slog/handlers`, `zap`) hit undefined-symbol errors, since the helper files aren't visible without the tag.
2. **If it "fixes" that by adding `-tags test` globally** (the only lever a plain Go/Gazelle consumer has, lacking per-target transitions), `log_test_init.go`'s `init()` — which reads `DD_LOG_LEVEL` from the environment and overrides the configured log level — now compiles into that consumer's production build too, silently making log level overridable via an environment variable outside of tests.

### Expected behavior

Test-only helper code should either:
- be named with a `_test.go` suffix (works everywhere, no tooling needs to guess — true for `log_test_init.go` and `slog/handlers/test_utils.go`, which appear to only be needed by the package's own tests), or
- if it must be importable by external test packages (the presumed reason it isn't `_test.go` today — non-`_test.go` files can be imported as a normal package dependency, `_test.go` files cannot — likely true for `logger_test_utils.go`, `slog/logger_test_utils.go`, and `slog/formatters/template.go`), be moved to a clearly-separated, explicitly-imported subpackage (e.g. `pkg/util/log/logtest`) rather than gated by an ad hoc build tag inside the main package.

Either fix removes the need for any external consumer to guess at and pass `-tags test`, and removes the risk of test-only code (especially `log_test_init.go`'s env-driven `init()`) being pulled into a production build by a consumer that doesn't have this repo's Bazel per-target tag scoping.

### Affected version

Present on `main` as of 2026-08-18 (`pkg/util/log` currently tagged through `v0.82.1`, with `v0.83.0`/`v0.84.0` in pre-release/devel). Introduced by #42856 (2025-11-07); not present before that PR.

### Suggested fix

Rename the non-`_test.go` files gated by `//go:build test` to end in `_test.go` where they're only ever needed by the package's own tests, or split the cross-package-importable helpers into a dedicated `logtest`-style subpackage.

### Reproduction Steps

```
$ cd pkg/util/log
$ go build ./...        # succeeds — production code is unaffected
$ go vet ./...           # fails:
slog/formatters/template_test.go:22:15: undefined: Template
slog/handlers/async_test.go:23:11: undefined: newMockInnerHandler
klog_redirect_test.go:27:10: undefined: LoggerFromWriterWithMinLevelAndLvlFuncMsgFormat
zap/zapcore_test.go:113:19: undefined: slog.LoggerFromWriterWithMinLevelAndFormat

$ go test ./...          # same undefined-symbol failures across pkg/util/log,
                          # pkg/util/log/slog/handlers, pkg/util/log/slog/formatters
```

This pattern was introduced deliberately (see #42856, "Move Default log function behind test build tag", merged 2025-11-07) to keep a bare stdout logger (`Default()`) out of production binaries — so any fix needs to preserve that intent, not just revert it.

**Comment by pgimalac** [comment]
As discussed directly together, this is expected and on purpose, we need the test build tag for test only code which is imported from other packages, and in particular when that code access unexported symbols of the package (in which case it can't be moved to a different package), or for an `init` function which we want to run for all tests, and only tests (eg. to initialize a simple default logger for tests).
Running tests in this repository requires using our tooling, and overall shouldn't cause issues from the outside.
