### PR TITLE
[system-probe] Fix ebpf tests

### PR DESCRIPTION
**Pull request by ISauve**
### What does this PR do?
Fixes the `TestTracerCompile` & `TestConntrackCompile`, which were broken by #7530

### Motivation

What inspired you to submit this pull request?

### Additional Notes

Anything else we should know when reviewing?

### Describe your test plan

Write there any instructions and details that should be tested during the QA.

### CODE REVIEW

**Review by heyronhay — APPROVED** [review]

**Review by leeavital — APPROVED** [review]

**Review by mx-psi — DISMISSED** [review]
There are still some issues

```
pkg/network/tracer/compile_test.go:17:5: undefined: err
pkg/network/tracer/compile_test.go:18:21: undefined: err
pkg/network/tracer/compile_test.go:25:5: undefined: err
pkg/network/tracer/compile_test.go:25:50: undefined: cflags
pkg/network/tracer/compile_test.go:26:21: undefined: err
```

**Review by brycekahle — APPROVED** [review]
