### PR TITLE
Replace Windows system probe socket endpoint localhost:3333 with named pipe

### PR DESCRIPTION
**Pull request by alexn-dd**
### What does this PR do?
This PR replaces the Windows system probe socket endpoint on default port 3333 with a fixed named pipe `\\.\pipe\dd_system_probe`.
The API where the system probe listener was created was renamed from `net.GetListener` to `net.GetSystemProbeListener` for better readability and auditing.
As an effect of this change, the Flare tests and a few others tests have been adjusted.
Source code has been included that builds a simple named pipe client tool, that allows manual CLI communication with the system probe named pipe server.
The port config for system probe on Windows (system_probe_config.sysprobe_socket) will be no-opt and will still remain unchanged for other OS platforms.

### Motivation
See: https://docs.google.com/document/d/1EJJ899nfXwXBU76-f69S6XP5vp1-q2tb0hUHbDbCwfA/edit

### Additional Notes
The existing endpoints with GRPC over sockets remain unchanged.

### Possible Drawbacks / Trade-offs
The named pipe is unsecured (no ACL).  This is on-par with the open socket today.  A future task will harden the named pipe.
Since the named pipe is fixed, it is possible for local experiments/tests to cause named pipe path collisions.  As  workaround, these local experiments should temporarily use a different named pipe path.

### Describe how to test/QA your changes
CI
Manually use named pipe client tool to query system probe server endpoint.
Manually step through process agent code when pinging system probe endpoint.
Manually verified console output without debugger when process agent connects to system probe.
aws-vault exec sso-agent-sandbox-account-admin -- inv new-e2e-tests.run --targets=./tests/process --run=TestWindowsTestSuite

### CODE REVIEW

File: cmd/agent/subcommands/flare/command_test.go [hunk 1]
```diff
@@ -80,12 +88,33 @@ func (c *commandTestSuite) getPprofTestServer() (tcpServer *httptest.Server, uni
 	return tcpServer, unixServer
 }
 
+func (c *commandTestSuite) restartSystemProbeTestServer() {
+	t := c.T()
+
+	if runtime.GOOS == "windows" {
```
Comment (derekwbrown) [inline cmd/agent/subcommands/flare/command_test.go:94]: instead of runtime conditional, suggest move empty implementation to `command_other_test.go`, and then have windows implementation here.

File: cmd/agent/subcommands/flare/command_test.go [hunk 2]
```diff
@@ -226,9 +259,22 @@ func (c *commandTestSuite) TestReadProfileDataErrors() {
...
+
 	data, err := readProfileData(10)
+
+	ClearConnectionFailures(mockSysProbeConfig, mockConfig)
+
 	require.Error(t, err)
-	require.Regexp(t, "^4 errors occurred:\n", err.Error())
+
+	if runtime.GOOS == "windows" {
+		// Windows has the security agent.
```
Comment (derekwbrown) [inline cmd/agent/subcommands/flare/command_test.go:272]: linux has a security agent, too.
I would expect this part of the test to be unchanged?

File: cmd/agent/subcommands/flare/command_test.go (hunk 1 above)
Comment (alexn-dd) [reply cmd/agent/subcommands/flare/command_test.go:94]: Agreed. Since the test had an existing runtime check convention, I tried to keep it that way, but generally it is better to split it out.

File: cmd/agent/subcommands/flare/command_test.go (hunk 2 above)
Comment (alexn-dd) [reply cmd/agent/subcommands/flare/command_test.go:272]: That is good to know about Linux and security agent.

The comment is incorrect.
This test simulates connection failures and originally had system-probe disabled, which was fine because other endpoints are also sockets (thus only 4 expected errors without counting system probe).  Now that system probe is a named pipe, this test explicitly enables system probe to test the (named pipe) connection failure, and thus expects to have 5 errors instead of 4.  I will split the specialized expectation into the windows file.

**Review by hmahmood — APPROVED** [review]

File: pkg/process/net/windows_pipe.go [hunk 3]
```diff
@@ -9,6 +9,16 @@ package net
 
 import (
 	"net"
+	"time"
+
+	"github.com/DataDog/datadog-agent/pkg/util/log"
+	"github.com/Microsoft/go-winio"
```
Comment (guyarb) [inline pkg/process/net/windows_pipe.go:15]: nit: 
```suggestion
	"github.com/Microsoft/go-winio"

	"github.com/DataDog/datadog-agent/pkg/util/log"
```

File: pkg/process/net/windows_pipe.go [hunk 4]
```diff
@@ -32,3 +61,17 @@ func (wp *WindowsPipeListener) GetListener() net.Listener {
...
+	// Unused netType and path
+
+	var timeout = time.Duration(5 * time.Second)
+
+	namedPipe, err := winio.DialPipe(SystemProbePipeName, &timeout)
+	if err != nil {
+		log.Errorf("error connecting to named pipe %s: %s", SystemProbePipeName, err)
+	}
+
+	return namedPipe, err
```
Comment (guyarb) [inline pkg/process/net/windows_pipe.go:76]: since the error is returned, is there a reason to log it? the caller isn't logging it?

**Review by guyarb — APPROVED** [review]
LGTM for USM Owned files

File: pkg/process/net/windows_pipe.go (hunk 4 above)
Comment (alexn-dd) [reply pkg/process/net/windows_pipe.go:76]: The existing higher level code still assume socket related errors.
This log makes it clear that the root failure came from a named pipe.

**Review by alai97 — APPROVED** [review]
Looks good for docs!

**Review by derekwbrown — APPROVED** [review]

File: pkg/process/net/windows_pipe.go (hunk 4 above)
Comment (guyarb) [reply pkg/process/net/windows_pipe.go:77]: > The existing higher level code (a few places) still assumes socket related errors.

what do you mean?

i'll be surprised that the error won't be logged by any of the callers
I suspect that currently we will have multiple logs with the same error

**Review by jeremy-hanna — APPROVED** [review]
👍 for ASC owned files

File: pkg/process/net/windows_pipe.go (hunk 4 above)
Comment (alexn-dd) [reply pkg/process/net/windows_pipe.go:77]: The following is common code calling the function and logging the error:
```
	conn, err := net.NewSystemProbeListener(cfg.SocketAddress)
	if err != nil {
		return fmt.Errorf("error creating IPC socket: %s", err)
	}
```

In this snippet, the existing error handler assumes a socket related error, which was fine because a socket was used for all OS platforms.  That is not the case anymore with this change.
That error handler would show something like:
`error creating IPC socket: \\.\pipe\dd_system_probe`,
which is not very sensical.  For someone triaging the log entry without context or tribal knowledge would be confuse.
The error log entry specifically stating that a named pipe connection fail will clarity this ambiguity bettter.

Frankly, I am a bit shocked that a simple error log entry would be scrutinized (versus other existing anti-patterns).

**Review by FlorentClarret — APPROVED** [review]

File: pkg/process/net/windows_pipe.go (hunk 4 above)
Comment (brycekahle) [reply pkg/process/net/windows_pipe.go:77]: Logging is considered "handling" the error, so logging and returning is usually a bad idea because the error would be "handled" twice. The better alternative is to wrap the error. I suggest something like:
```
if err != nil {
    return nil, fmt.Errorf("named pipe %s: %w", SystemProbePipeName, err)
}
```

Comment (brycekahle) [reply pkg/process/net/windows_pipe.go:77]: Also, any reason you cannot change the common code error to be `error creating IPC: %s` and moving `socket` or `named pipe` deeper where appropriate?

File: pkg/process/net/windows_pipe.go [hunk 5]
```diff
@@ -17,10 +28,29 @@ type WindowsPipeListener struct {
...
-	l, err := net.Listen("tcp", socketAddr)
-	return &WindowsPipeListener{l, "path"}, err
+// Create a standardized named pipe server and with hardened ACL
+func newPipeListener(namedPipeName string) (net.Listener, error) {
+	config := winio.PipeConfig{
+		InputBufferSize:  namedPipeInputBufferSize,
+		OutputBufferSize: namedPipeOutputBufferSize,
+	}
+
+	// TODO: Apply hardened ACL
```
Comment (xornivore) [inline pkg/process/net/windows_pipe.go:38]: Should this ACL be part of the changes here?

Comment (alexn-dd) [reply pkg/process/net/windows_pipe.go:38]: Not for this PR.  This is on-part with the previous socket-based endpoint (port 3333), since it was an open port.

**Review by xornivore — APPROVED** [review]
LGTM for Processes owned files.

File: pkg/process/net/windows_pipe.go (hunk 4 above)
Comment (alexn-dd) [reply pkg/process/net/windows_pipe.go:77]: I was aiming to minimize churn as much as possible, but if it is fine, I can move the specialized error messages deeper and make it less ambiguous.  Thanks!

Comment (guyarb) [reply pkg/process/net/windows_pipe.go:77]: you're still logging & returning an error

File: pkg/process/net/windows_pipe.go [hunk 6]
```diff
@@ -71,7 +69,7 @@ func DialSystemProbe(_ string, _ string) (net.Conn, error) {
 
 	namedPipe, err := winio.DialPipe(SystemProbePipeName, &timeout)
 	if err != nil {
-		log.Errorf("error connecting to named pipe %s: %s", SystemProbePipeName, err)
+		return nil, fmt.Errorf("error connecting to named pipe %s : %s", SystemProbePipeName, err)
 	}
 
 	return namedPipe, err
```
Comment (guyarb) [inline pkg/process/net/windows_pipe.go:75]:
```suggestion
	return namedPipe, nil
```

File: cmd/agent/subcommands/flare/command_test.go [hunk 7]
```diff
@@ -86,6 +94,8 @@ func TestCommandTestSuite(t *testing.T) {
 
 func (c *commandTestSuite) TestReadProfileData() {
 	t := c.T()
+	RestartSystemProbeTestServer(c)
```
Comment (brycekahle) [inline cmd/agent/subcommands/flare/command_test.go:97]: I'd suggest starting the server in tests that need it, and shutting it down with `t.Cleanup`. That would get rid of the need for these restart calls. Generally, leaving things running after a test completes is bad practice.

File: test/new-e2e/tests/sysprobe-functional/usmtest/NamedPipeCmd.exe
Comment (brycekahle) [inline test/new-e2e/tests/sysprobe-functional/usmtest/NamedPipeCmd.exe:1]: Is this a built version of `tools/NamedPipeCmd`? Any way we can build this during the tests? That would prevent a stale executable and not need to commit a 16MB file to the git repo.

File: pkg/process/net/common_windows.go [hunk 8]
```diff
@@ -28,8 +28,14 @@ const (
 	procStatsURL = "http://localhost:3333/" + string(sysconfig.ProcessModule) + "stats"
 	// pingURL is not used in windows, the value is added to avoid compilation error in windows
 	pingURL = "http://localhost:3333/" + string(sysconfig.PingModule) + "/ping/"
+
+	// SystemProbeProductionPipeName is the production named pipe for system-probe
+	SystemProbeProductionPipeName = `\\.\pipe\dd_system_probe`
 )
 
+// SystemProbePipeName is the effective named pipe path for system-probe
+var SystemProbePipeName = SystemProbeProductionPipeName
```
Comment (brycekahle) [inline pkg/process/net/common_windows.go:37]: It seems that continuing to use a configuration value for the pipe name might be a good idea. That would likely prevent the need for exported globals. WDYT?

File: pkg/process/net/windows_pipe.go [hunk 9]
```diff
@@ -32,3 +60,17 @@ func (wp *WindowsPipeListener) GetListener() net.Listener {
 func (wp *WindowsPipeListener) Stop() {
 	wp.conn.Close()
 }
+
+// DialSystemProbe connects to the system-probe service endpoint
+func DialSystemProbe(_ string, _ string) (net.Conn, error) {
```
Comment (brycekahle) [inline pkg/process/net/windows_pipe.go:65]: nit: I expected this function in `common_windows.go` because the other OS versions were in `common_*.go`

File: test/new-e2e/tests/sysprobe-functional/usmtest/NamedPipeCmd.exe
Comment (derekwbrown) [reply test/new-e2e/tests/sysprobe-functional/usmtest/NamedPipeCmd.exe:1]: yes, it's a built version of that.
NOt that I can think of, but am open to suggestions.
It's used in the`e2e` tests; those tests are run from a linux bulder, even for windows.

File: pkg/process/net/windows_pipe.go (hunk 9 above)
Comment (alexn-dd) [reply pkg/process/net/windows_pipe.go:65]: The original placeholder function was located in windows_pipe.go.  Since future iterations intend to add more specialized Windows named pipe logic, it makes sense to separate it from the generic common_windows.go. It is easy to bloat a "common" file over time.

File: pkg/process/net/common_windows.go (hunk 8 above)
Comment (alexn-dd) [reply pkg/process/net/common_windows.go:37]: The business case as of now is that the named pipe will not be externally configurable.  
It is also not reasonable/user-friendly to reuse the the existing config field "system_probe_config.sysprobe_socket" for a named pipe path.
AFAIK, the main reason for the configurable field "system_probe_config.sysprobe_socket" is to address port conflicts, which with the dedicated named pipe will be resolved.
The only use case that requires a named pipe override is for a local e2e test running SxS with an existing Datadog install.

File: cmd/agent/subcommands/flare/command_test.go (hunk 7 above)
Comment (alexn-dd) [reply cmd/agent/subcommands/flare/command_test.go:97]: Good call.

File: pkg/process/net/common_windows.go (hunk 8 above)
Comment (brycekahle) [reply pkg/process/net/common_windows.go:37]: Having an exported global that is overridden is not a good abstraction, and a code smell.  I agree that "socket" could be a confusing name for the configuration variable. We have a lot of configuration variables that are not documented and realistically not intended to be changed by customers, but they allow us to retain that flexibility (such as for tests).

**Comment by brycekahle** [comment]
`cmd/system-probe/config/config_windows.go` still has `ValidateSocketAddress` that expects a string of `host:port`.

File: pkg/process/net/common_windows.go (hunk 8 above)
Comment (alexn-dd) [reply pkg/process/net/common_windows.go]: I removed the exported global and instead introduce a function OverrideSystemProbeNamedPipePath, which is used by tests only.

File: pkg/process/net/windows_pipe.go [hunk 10]
```diff
@@ -39,16 +42,22 @@ func newPipeListener(namedPipeName string) (net.Listener, error) {
 	return winio.ListenPipe(namedPipeName, &config)
 }
 
+// OverrideSystemProbeNamedPipePath sets the active named pipe path for System Probe connections.
+// This is used by tests only to avoid conflicts with an existing locally installed Datadog agent.
```
Comment (brycekahle) [inline pkg/process/net/windows_pipe.go:46]: You can enforce test-only by putting this function in a file with a build tag of `test`

**Review by brycekahle — APPROVED** [review]
looks like you need to fix the non-windows tests
