### PR TITLE
[network] ebpf build on kernel 5.18

### PR DESCRIPTION
**Pull request by nplanel**
kernel 5.18 define TASK_COMM_LEN in linux/sched.h and would need to be included for prebuild offset-guess

Stderr:

In file included from /lib/modules/5.18.5-arch1-1/build/include/linux/percpu-rwsem.h:7:
In file included from /lib/modules/5.18.5-arch1-1/build/include/linux/rcuwait.h:6:
In file included from /lib/modules/5.18.5-arch1-1/build/include/linux/sched/signal.h:7:
/lib/modules/5.18.5-arch1-1/build/include/linux/sched.h:282:2: error: expected identifier
        TASK_COMM_LEN = 16,
        ^
./pkg/network/ebpf/c/prebuilt/offset-guess.h:7:23: note: expanded from macro 'TASK_COMM_LEN'

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Comment by brycekahle** [comment]
Is the problem that we define `TASK_COMM_LEN` and `sched.h` later complains because it is already defined?

**Review by brycekahle — APPROVED** [review]
