### PR TITLE
Fix signature to match change done in #2814

### PR DESCRIPTION
**Pull request by mfpierre**
### What does this PR do?

Fixes `not enough arguments in call to docker.HostnameProvider have () want (string)`

### Additional Notes

Introduced in #2814

### CODE REVIEW

**Review by xvello — APPROVED** [review]
Good catch!

**Review by olivielpeau — APPROVED** [review]
LGTM!

I don't understand why this wasn't caught by the CI though, do you know why?

**Comment by xvello** [comment]
Interface checks are done at runtime in golang (while they are checked at compilation in Java for example). On top of the performance penalty, this makes this kind of issues hard to catch.

**Comment by mfpierre** [comment]
The error is trigger by having the `kubelet` build tag, but not the `docker` one because the call to this function is made in https://github.com/DataDog/datadog-agent/blob/master/pkg/util/kubernetes/kubelet/kubelet.go#L505
We don't have this combination of tags in any of our tests
