### PR TITLE
Fix `windows-lint-go` CI job

### PR DESCRIPTION
**Pull request by L3n41c**
### What does this PR do?

Fix the Windows lint CI job.

### Motivation

The job is currently failing with this error:
```
Linters for module C:\buildroot\datadog-agent\test\new-e2e failed (base flavor)
Linter failures:
level=error msg="[linters_context] typechecking error: : # github.com/DataDog/datadog-agent/test/new-e2e/ndm/snmp\nndm\\snmp\\snmpTestEnv.go:96:19: undefined: docker.NewAgentDockerInstaller\nndm\\snmp\\snmpTestEnv.go:98:11: undefined: docker.WithComposeContent\nndm\\snmp\\snmpTestEnv.go:99:11: undefined: docker.WithPulumiResources"
level=error msg="[linters_context] typechecking error: C:\\buildroot\\datadog-agent\\test\\new-e2e\\scenarios\\ndm\\main.go:12:2: could not import github.com/DataDog/datadog-agent/test/new-e2e/ndm/snmp (-: # github.com/DataDog/datadog-agent/test/new-e2e/ndm/snmp\nndm\\snmp\\snmpTestEnv.go:96:19: undefined: docker.NewAgentDockerInstaller\nndm\\snmp\\snmpTestEnv.go:98:11: undefined: docker.WithComposeContent\nndm\\snmp\\snmpTestEnv.go:99:11: undefined: docker.WithPulumiResources)"
```

### Additional Notes

The Windows lint CI job has been broken by #18286 because it bumped the version of `test-infra-definitions` and the new version brought a big refactoring.

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Comment by TCheruy** [comment]
👋🏻 I think #18439 already handle this

**Comment by L3n41c** [comment]
I already discussed with @chouetz and it turned out that #18439 isn’t fixing.

**Review by TCheruy — APPROVED** [review]

**Review by chouetz — APPROVED** [review]
Many thanks

File: test/new-e2e/ndm/snmp/snmpTestEnv.go [hunk 1]
```diff
@@ -93,10 +94,10 @@ func NewTestEnv() (*TestEnv, error) {
 		envVars := map[string]string{"DATA_DIR": dataPath, "CONFIG_DIR": configPath}
 		composeDependencies := []pulumi.Resource{createDataDirCommand, configCommand}
 		composeDependencies = append(composeDependencies, fileCommands...)
-		_, err = docker.NewAgentDockerInstaller(
-			vm.UnixVM,
```
Comment (KevinFairise2) [inline test/new-e2e/ndm/snmp/snmpTestEnv.go:97]: I think this will not have the expected behaviour. With the new `NewDaemon` function, the VM is created automatically here in the function. It means here that all these [line](https://github.com/DataDog/datadog-agent/pull/18453/files#diff-4b47c437598feca25c1b2dacb0bc9f7c0acd5cf48dcbc333d87610b9a3fb158eL55-R91) will create/copy file on a VM that will not be used by the `NewDaemon` function

**Comment by chouetz** [comment]
Replaced by https://github.com/DataDog/datadog-agent/pull/18465
